mhdhejazi/CoronaTracker

- README.md
Thanks @MhdHejazi for this project, I simply wanted to simplify installation in macOS for users who already use Homebrew.
1. Added Corona Tracker to Homebrew (pull request [#78680](https://github.com/Homebrew/homebrew-cask/pull/78680))
2. updated (not by me) to latest version (pull request [#78718](https://github.com/Homebrew/homebrew-cask/pull/78718))
3. this pull request just to be included in project README as possible installation in macOS
> Added brew cask command in README

- Corona/Localization/it.lproj/Localizable.strings
> Italian localization

- Corona/Localization/it.lproj/Localizable.strings
Added new chart.delta and data.source translations.
> New translations update

- Corona/Localization/sv.lproj/Localizable.strings
Added 2 new string translations to Swedish!
> Added 2 new string translations to Swedish!

- Corona.xcodeproj/project.pbxproj
> Embed and sign dynamic frameworks

- Corona/Localization/zh-HANS.lproj/Localizable.strings
I have added the translation for Simplified Chinese users. Thank you for your hard work creating such a simple but useful app.
> Added Simplified Chinese (zh-HANS) translation

- Corona/Localization/sp.proj/Localizable.strings
Hello! I translated the localizable strings to Spanish.
> Add Spanish translation

- Corona/Localization/it.lproj/Localizable.strings
> Updated Italian Localization

- Corona/Controller/RegionDataCell.swift
- Corona/Generated/Strings.swift
- Corona/Localization/Base.lproj/Localizable.strings
- Corona/Localization/fr.lproj/Localizable.strings
Create a localized string for Copy menu item, and update French localized strings
> Add localized « Copy » string and update French localization

- Corona/Localization/it.lproj/Localizable.strings
Update Italian Localization for "menu.copy" key
> Update Italian Localization

- Corona/Controller/Chart/ChartController.swift
- Corona/Controller/Map/MapController.swift
- Corona/Controller/Region/RegionCells/AuthorInfoCell.swift
- Corona/Controller/Region/RegionCells/DataSourceCell.swift
- Corona/Controller/Region/RegionPanelController.swift
This PR improves IBAction usage.  It also slightly improves internal documentation.
> added private to IBActions and added mark comment

- Corona.xcodeproj/project.pbxproj
- Corona/Localization/ko.lproj/Localizable.strings
Update South Korea Localization
> Update South Korea Localization

- Corona/Localization/ar.lproj/Localizable.strings
Translated to the Arabic Language.
> Adding Arabic Language

- Corona/Localization/nb_NO.lproj
> Add Norwegian Bokmål language

- Corona.xcodeproj/project.pbxproj
- Corona/Localization/id.lproj/Localizable.strings
Signed-off-by: Niko Tidar Lantang Perkasa <me@rndtx.id>
> Add Indonesian Translation

- Corona.xcodeproj/project.pbxproj
- Corona/Localization/zh-Hant-TW.lproj/Localizable.strings
Hi mhdhejazi 
I am from Taiwan
this is about Chinese(Traditional) update , hope can help
> Update Chinese(Traditional) _ Taiwan Localizable.strings 

- README.md
Signed-off-by: Niko Tidar Lantang Perkasa <me@rndtx.id>
> Update README.md for list translate contributor

- Corona.xcodeproj/project.pbxproj
- Corona/Data/DataManager.swift
- Corona/Service/AustriaDataService.swift
- Corona/Service/BMSGPKDataService.swift
Added subregions for Austria, did it very similar to the RKI (german) solution.
> Addes subregions for Austria

- Corona/Localization/de.lproj/Localizable.strings
add 2 strings and sort like it is in Localizable.strings (Base)
> complete German translation and sort

- Corona.xcodeproj/project.pbxproj
- Corona/Localization/el.lproj/Localizable.strings
Resources for the Greek language.
> Greek localization

- Corona/Localization/pt.lproj/Localizable.strings
Just correcting the word "Logaritimica" (correct is "Logarítmica")
> Update Localizable.strings (pt)
